/**
 * Rust compile driver.
 *
 * Turns a directory of ordinary Rust into a `.wasm`, generating the cargo
 * manifest if the developer has not written one. Adding another language means
 * adding a sibling of this file — nothing outside `drivers/` changes.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { run } from '../toolchain.ts';
import type { CompileRequest, CompileResult } from '../types.ts';

const TARGET = 'wasm32-unknown-unknown';

/**
 * A cargo manifest tuned for small, fast WASM.
 *
 * Generated rather than required, so a module can be a single .rs file with no
 * build configuration to learn.
 */
// The public repo cargo can pull the crossnative crate from when this package is
// installed from npm (no monorepo crate path on disk). Overridable for forks.
const CRATE_GIT =
  process.env.CROSSNATIVE_CRATE_GIT ?? 'https://github.com/melodyLeonard/cross-native';

// Pin the git dependency to a release tag so builds are reproducible and match
// the installed package rather than floating on the default branch. Bumped per
// release (see docs/releasing.md); overridable for forks and local testing.
const CRATE_TAG = process.env.CROSSNATIVE_CRATE_TAG ?? 'crossnative-v0.1.0-alpha.6';

function defaultManifest(
  crateName: string,
  crossnativeDep: string,
  libPath: string
): string {
  return `# Generated by CrossNative. Edit freely, it will not be overwritten.
[package]
name = "${crateName}"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]
path = "${libPath}"

[dependencies]
crossnative = ${crossnativeDep}

[profile.release]
opt-level = 3
lto = true
strip = "symbols"
`;
}

async function exists(path: string): Promise<boolean> {
  try {
    await readFile(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Find the crate's library entry point, so a single loose `.rs` works without
 * the author arranging it into `src/lib.rs`.
 *
 * Preference order: an explicit entry, then the conventional `src/lib.rs`, then
 * a top-level `lib.rs`, then the only `.rs` in the directory.
 */
async function findLibEntry(request: CompileRequest): Promise<string> {
  const { readdir } = await import('node:fs/promises');

  if (request.entryFile) return request.entryFile;
  if (await exists(join(request.sourceDir, 'src', 'lib.rs'))) return 'src/lib.rs';
  if (await exists(join(request.sourceDir, 'lib.rs'))) return 'lib.rs';

  const rustFiles = (await readdir(request.sourceDir)).filter((f) => f.endsWith('.rs'));
  if (rustFiles.length === 1) return rustFiles[0];
  if (rustFiles.length === 0) {
    throw new Error(`No .rs file found in ${request.sourceDir}`);
  }
  throw new Error(
    `Multiple .rs files in ${request.sourceDir} and no src/lib.rs. ` +
    `Point CrossNative at one file, or arrange them under src/lib.rs.`
  );
}

/**
 * Make sure the directory is a buildable crate.
 *
 * If there is no Cargo.toml we write one pointing at whatever the author's
 * entry file actually is — their sources are never moved.
 */
async function ensureCrate(request: CompileRequest): Promise<void> {
  const manifestPath = join(request.sourceDir, 'Cargo.toml');
  if (await exists(manifestPath)) return;

  const libPath = await findLibEntry(request);
  // Use the local crate in a monorepo checkout (fast, offline); fall back to the
  // published crate over git when installed from npm, where that path is absent.
  const localCrate = join(request.runtimeCratePath, 'Cargo.toml');
  const dep = (await exists(localCrate))
    ? `{ path = "${request.runtimeCratePath}" }`
    : `{ git = "${CRATE_GIT}", package = "crossnative", tag = "${CRATE_TAG}" }`;
  await writeFile(manifestPath, defaultManifest(request.moduleName, dep, libPath));
}

export async function compileRust(request: CompileRequest): Promise<CompileResult> {
  await ensureCrate(request);

  const { code, stderr } = await run(
    ['cargo', 'build', '--target', TARGET, '--release'],
    request.sourceDir
  );

  if (code !== 0) {
    return {
      ok: false,
      // cargo's own diagnostics are better than anything we could synthesise,
      // so they are passed through untouched.
      error: stderr.trim() || `cargo exited with code ${code}`,
    };
  }

  const artifact = join(
    request.sourceDir,
    'target',
    TARGET,
    'release',
    `${request.moduleName.replace(/-/g, '_')}.wasm`
  );

  if (!(await exists(artifact))) {
    return {
      ok: false,
      error:
        `Build succeeded but no .wasm was produced at ${artifact}.\n` +
        `Check that Cargo.toml sets crate-type = ["cdylib"].`,
    };
  }

  return { ok: true, artifactPath: artifact };
}
