/**
 * Embedding a compiled module into the JavaScript bundle.
 *
 * Metro has no loader for .wasm and asset resolution differs between iOS,
 * Android, dev and release. Embedding sidesteps all of it. The Metro
 * transformer will make this invisible; until then it is an explicit step.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname } from 'node:path';

/** Read a compiled artifact and return it as base64. */
export async function toBase64(artifactPath: string): Promise<string> {
  return (await readFile(artifactPath)).toString('base64');
}

/** Write an artifact out as a TypeScript module exporting base64. */
export async function embedWasm(
  artifactPath: string,
  outputPath: string
): Promise<number> {
  const bytes = await readFile(artifactPath);

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(
    outputPath,
    `// Generated by CrossNative — do not edit.\n` +
    `// Source: ${artifactPath} (${bytes.length} bytes)\n\n` +
    `export const WASM_BASE64 =\n  '${bytes.toString('base64')}';\n`
  );

  return bytes.length;
}
