/**
 * Native static-library build for the iOS FFI path.
 *
 * iOS forbids loading executable code at runtime, so on iOS the fast path is to
 * compile the source to a native static library, link it into the app, and call
 * it over the C ABI — the same route Rust's `#[crossnative]` takes. This module
 * does that for Zig: it parses the plain `export fn` signatures, generates a
 * dispatch shim that implements the `crossnative_call_<suffix>` /
 * `crossnative_manifest_<suffix>` protocol the C++ SharedLibraryModule expects,
 * and compiles both to a static `.a` for the requested Apple target.
 *
 * The user's `.zig` stays exactly the plain source the WASM path uses — the shim
 * is generated, mirroring how the Rust macro generates its dispatcher.
 */

import { readFile, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';
import { run } from './toolchain.ts';

/** A parsed `export fn` signature. */
export interface FnSig {
  name: string;
  params: { name: string; type: string }[];
  returns: string; // "void" for no return
}

const NUMERIC = new Set([
  'f64', 'f32', 'i8', 'i16', 'i32', 'i64', 'u8', 'u16', 'u32', 'u64', 'usize', 'isize',
]);

/** Parse `export fn NAME(a: T, b: U) RET {` declarations from Zig source. */
export function parseZigExports(source: string): FnSig[] {
  const sigs: FnSig[] = [];
  // export fn name(params) ReturnType {   — ReturnType may be absent (void).
  const re = /export\s+fn\s+([A-Za-z_]\w*)\s*\(([^)]*)\)\s*([A-Za-z_]\w*)?\s*\{/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(source)) !== null) {
    const [, name, paramList, ret] = m;
    const params = paramList
      .split(',')
      .map(p => p.trim())
      .filter(Boolean)
      .map(p => {
        const [pname, ptype] = p.split(':').map(s => s.trim());
        return { name: pname, type: ptype };
      });
    sigs.push({ name, params, returns: ret ?? 'void' });
  }
  return sigs;
}

/** How one argument is read from the JSON args array in the generated shim. */
function readArg(type: string, index: number): string {
  const at = `args.items[${index}]`;
  if (type === 'bool') return `(argF64(${at}) != 0)`;
  if (type === 'f64') return `argF64(${at})`;
  if (type === 'f32') return `@as(f32, @floatCast(argF64(${at})))`;
  if (NUMERIC.has(type)) return `@as(${type}, @intFromFloat(argF64(${at})))`;
  throw new Error(
    `linked build supports only numeric/bool parameters; got '${type}'. ` +
    `Arrays and strings are not supported on the iOS linked path yet.`
  );
}

/** The `respond(...)` call that encodes one function's result. */
function encodeResult(sig: FnSig): string {
  // Call the user's exported symbol directly (declared `extern` in the shim),
  // rather than through @import — `export fn` is not `pub`, so it isn't
  // reachable by name, but its C symbol is.
  const call = `${sig.name}(${sig.params.map((p, i) => readArg(p.type, i)).join(', ')})`;
  if (sig.returns === 'void') {
    return `{ ${call}; return respond("{{\\"success\\":true,\\"result\\":null,\\"outputs\\":[]}}", .{}); }`;
  }
  if (sig.returns === 'bool') {
    return `return respond("{{\\"success\\":true,\\"result\\":{},\\"outputs\\":[]}}", .{${call}});`;
  }
  if (NUMERIC.has(sig.returns)) {
    return `return respond("{{\\"success\\":true,\\"result\\":{d},\\"outputs\\":[]}}", .{${call}});`;
  }
  throw new Error(`linked build supports only numeric/bool/void returns; got '${sig.returns}'`);
}

/** The manifest JSON (as a Zig string literal body, braces escaped for fmt). */
function manifestLiteral(sigs: FnSig[]): string {
  const json = JSON.stringify(
    sigs.map(s => ({
      name: s.name,
      params: s.params.map(p => ({ name: p.name, type: p.type })),
      returns: s.returns,
    }))
  );
  // Escape for a Zig string literal, and double braces so std.fmt leaves them.
  return json.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/[{}]/g, b => b + b);
}

/** Generate the dispatch shim source that imports the user's file. */
export function generateZigDispatch(entryFile: string, sigs: FnSig[], suffix: string): string {
  const dispatch = sigs
    .map(s => `    if (std.mem.eql(u8, func, "${s.name}")) ${encodeResult(s)}`)
    .join('\n');

  // Importing the user file forces its `export fn`s to be compiled and emitted;
  // we then call them through `extern` declarations, since export is not pub.
  const externs = sigs
    .map(s => {
      const params = s.params.map(p => `${p.name}: ${p.type}`).join(', ');
      const ret = s.returns === 'void' ? 'void' : s.returns;
      return `extern fn ${s.name}(${params}) ${ret};`;
    })
    .join('\n');

  return `// Generated by @cross-native/compiler — do not edit.
const std = @import("std");
const user = @import(${JSON.stringify(entryFile)});
comptime {
    _ = user; // force the user module (and its exports) into the compilation
}

${externs}

const alloc = std.heap.c_allocator;
var last_result: ?[:0]u8 = null;

fn respond(comptime fmt: []const u8, args: anytype) [*:0]const u8 {
    if (last_result) |b| alloc.free(b);
    const s = std.fmt.allocPrintSentinel(alloc, fmt, args, 0) catch return "";
    last_result = s;
    return s.ptr;
}

fn argF64(v: std.json.Value) f64 {
    return switch (v) {
        .float => |f| f,
        .integer => |i| @floatFromInt(i),
        .number_string => |s| std.fmt.parseFloat(f64, s) catch 0,
        else => 0,
    };
}

export fn crossnative_call${suffix}(req: [*:0]const u8) [*:0]const u8 {
    const request = std.mem.span(req);
    var parsed = std.json.parseFromSlice(std.json.Value, alloc, request, .{}) catch
        return respond("{{\\"success\\":false,\\"error\\":\\"bad request JSON\\"}}", .{});
    defer parsed.deinit();
    const root = parsed.value;
    const func = (root.object.get("function") orelse
        return respond("{{\\"success\\":false,\\"error\\":\\"no function\\"}}", .{})).string;
    const args = (root.object.get("args") orelse
        return respond("{{\\"success\\":false,\\"error\\":\\"no args\\"}}", .{})).array;
    _ = &args;

${dispatch}

    return respond("{{\\"success\\":false,\\"error\\":\\"function not found\\"}}", .{});
}

export fn crossnative_manifest${suffix}() [*:0]const u8 {
    return respond("${manifestLiteral(sigs)}", .{});
}
`;
}

export interface NativeLibRequest {
  sourceDir: string;
  entryFile: string; // relative to sourceDir, e.g. compute.zig
  target: string; // e.g. aarch64-ios-simulator, aarch64-ios
  symbol: string; // suffix, e.g. "_zig"
  outPath: string; // where to write the .a
}

export interface NativeLibResult {
  ok: boolean;
  artifactPath?: string;
  error?: string;
}

function resolveZig(): string {
  return process.env.CROSSNATIVE_ZIG ?? 'zig';
}

/** Generate the shim and compile it + the user source into one static lib. */
export async function compileZigNativeLib(req: NativeLibRequest): Promise<NativeLibResult> {
  const source = await readFile(join(req.sourceDir, req.entryFile), 'utf8');
  const sigs = parseZigExports(source);
  if (sigs.length === 0) {
    return { ok: false, error: `no 'export fn' declarations found in ${req.entryFile}` };
  }

  let shim: string;
  try {
    shim = generateZigDispatch(req.entryFile, sigs, req.symbol);
  } catch (e) {
    return { ok: false, error: (e as Error).message };
  }

  const shimName = `cn_dispatch${req.symbol}.zig`;
  await writeFile(join(req.sourceDir, shimName), shim);

  const { code, stderr } = await run(
    [
      resolveZig(), 'build-lib', shimName,
      '-target', req.target,
      '-O', 'ReleaseFast',
      '-lc',                    // std.heap.c_allocator + the Apple libc
      `-femit-bin=${req.outPath}`,
    ],
    req.sourceDir
  );

  if (code !== 0) {
    return { ok: false, error: stderr.trim() || `zig build-lib exited with ${code}` };
  }
  return { ok: true, artifactPath: req.outPath };
}
