//! CrossNative Rust Runtime
//! 
//! This crate provides the Rust implementation for CrossNative,
//! allowing Rust functions to be called from React Native via JSI.

use std::collections::HashMap;
use std::sync::Arc;

use anyhow::Result;
use parking_lot::RwLock;
use tokio::runtime::Runtime;

// Re-export macros
pub mod macros;

// Module registry
mod registry;
use registry::ModuleRegistry;

// Type conversions
mod types;
pub use types::*;

// Runtime
mod runtime;
use runtime::NativeRuntime;

/// Global module registry - stores all registered native modules
static REGISTRY: RwLock<ModuleRegistry> = RwLock::new(ModuleRegistry::new());

/// Global async runtime for executing native functions
lazy_static::lazy_static! {
    static ref ASYNC_RUNTIME: Arc<Runtime> = {
        let rt = tokio::runtime::Builder::new_multi_thread()
            .worker_threads(num_cpus::get())
            .max_blocking_threads(512)
            .enable_all()
            .build()
            .expect("Failed to create Tokio runtime");
        
        Arc::new(rt)
    };
}

/// Initialize the Rust runtime
/// Called once when the native module is loaded
#[no_mangle]
pub extern "C" fn cross_native_init() -> i32 {
    env_logger::init();
    log::info!("CrossNative Rust runtime initialized");
    0 // Success
}

/// Register a module with the runtime
/// 
/// # Safety
/// This function is called from C++ via JSI
#[no_mangle]
pub unsafe extern "C" fn cross_native_register_module(
    module_id: *const libc::c_char,
    module_ptr: *mut libc::c_void,
) -> i32 {
    let id = match std::ffi::CStr::from_ptr(module_id).to_str() {
        Ok(s) => s.to_string(),
        Err(_) => return -1,
    };
    
    log::info!("Registering module: {}", id);
    
    let mut registry = REGISTRY.write();
    registry.register(id, module_ptr);
    
    0
}

/// Call a function on a registered module
/// 
/// # Safety
/// This function is called from C++ via JSI
#[no_mangle]
pub unsafe extern "C" fn cross_native_call(
    module_id: *const libc::c_char,
    method_id: *const libc::c_char,
    args_json: *const libc::c_char,
) -> *mut libc::c_char {
    let module_id = match std::ffi::CStr::from_ptr(module_id).to_str() {
        Ok(s) => s,
        Err(_) => return std::ptr::null_mut(),
    };
    
    let method_id = match std::ffi::CStr::from_ptr(method_id).to_str() {
        Ok(s) => s,
        Err(_) => return std::ptr::null_mut(),
    };
    
    let args = match std::ffi::CStr::from_ptr(args_json).to_str() {
        Ok(s) => s,
        Err(_) => return std::ptr::null_mut(),
    };
    
    // Parse arguments
    let parsed_args: Vec<serde_json::Value> = match serde_json::from_str(args) {
        Ok(v) => v,
        Err(_) => return std::ptr::null_mut(),
    };
    
    // Get module from registry
    let registry = REGISTRY.read();
    let module = match registry.get(module_id) {
        Some(m) => m,
        None => {
            log::error!("Module not found: {}", module_id);
            return std::ptr::null_mut();
        }
    };
    
    // Call the method (this would be generated by UniFFI)
    log::info!("Calling {}.{}", module_id, method_id);
    
    // For now, return a simple success response
    let result = serde_json::json!({
        "status": "ok",
        "module": module_id,
        "method": method_id,
        "args_received": parsed_args.len()
    });
    
    let result_str = serde_json::to_string(&result).unwrap_or_default();
    
    // Return as C string (caller must free)
    match std::ffi::CString::new(result_str) {
        Ok(c_str) => c_str.into_raw(),
        Err(_) => std::ptr::null_mut(),
    }
}

/// Free a string returned by cross_native_call
/// 
/// # Safety
/// Must only be called with pointers returned by cross_native_call
#[no_mangle]
pub unsafe extern "C" fn cross_native_free_string(ptr: *mut libc::c_char) {
    if !ptr.is_null() {
        let _ = std::ffi::CString::from_raw(ptr);
    }
}

/// Get the async runtime handle
pub fn get_runtime() -> Arc<Runtime> {
    ASYNC_RUNTIME.clone()
}

/// Spawn a task on the async runtime
pub fn spawn_task<F>(future: F) -> tokio::task::JoinHandle<F::Output>
where
    F: std::future::Future + Send + 'static,
    F::Output: Send + 'static,
{
    ASYNC_RUNTIME.spawn(future)
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_runtime_creation() {
        let rt = get_runtime();
        assert!(true); // If we got here, runtime was created
    }
    
    #[tokio::test]
    async fn test_spawn_task() {
        let handle = spawn_task(async {
            42
        });
        
        let result = handle.await.unwrap();
        assert_eq!(result, 42);
    }
}
